// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheBluesland.Data;

#nullable disable

namespace TheBluesland.Data.Migrations
{
    [DbContext(typeof(TheBlueslandDbContext))]
    [Migration("20260903100512_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TheBluesland.Data.Entities.SpotifyPlaylistCacheEntry", b =>
                {
                    b.Property<string>("SpotifyPlaylistId")
                        .HasColumnType("text")
                        .HasColumnName("spotify_playlist_id");

                    b.PrimitiveCollection<string[]>("Artists")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("artists");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_image_url");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SpotifySnapshotId")
                        .HasColumnType("text")
                        .HasColumnName("spotify_snapshot_id");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("synced_at");

                    b.Property<int>("TrackCount")
                        .HasColumnType("integer")
                        .HasColumnName("track_count");

                    b.HasKey("SpotifyPlaylistId");

                    b.ToTable("spotify_playlist_cache", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
